name: Lolos
favicon: null
layout_spectrum: 0.19110493827611208
typography_spectrum: 0.15720126684755087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.496625158470124
  lightness: 0.6449407732579857
  saturation: 0.9074184091296047
  rhythmicContrast: 0.27668092167004943
purpose: []
